---
    - name: restart nginx
      service: name=nginx state=reloaded

      
    - name: start mysql
      service: name=mysql
               enabled=yes
               state=started

    - name: restart mysql
      service: name=mysql
               enabled=yes
               state=restarted
        
